### PR TITLE
Optimization WIP

### PR DESCRIPTION
**Pull request by tmfink**
Addresses #2 

- [x] Improve compile times
    - [x] Do not download/require `bindgen` unnecessarily
    - [x] Eliminate unnecessary `lazy_static`
- [X] ~Document bindings~ (deferred to issue #6)
- [x] Make feature flags more coherent
- [x] Fix mis/unused features
- [x] Make bindgen no longer the default (use pre-generated bindings by default)
- [ ] Reconsider Git submodule
- [ ] Justify bindgen

### CODE REVIEW

**Comment by m4b** [comment]
Haven't had a chance to glance at this but this has some good info: https://users.rust-lang.org/t/help-creating-a-sys-crate/12624/3?u=m4b

I also didn't realize that pkgconfig doesn't work on windows :/

I think in that case we should probably build the bundled bindings unconditionally?

**Comment by tmfink** [comment]
**Build times (user seconds)**:

Commit | Clean build | Rebuild
-- | -- | --
Before `bindgen` (fcc8eaca8c9f95a5b3be005faa93d9421f707355) | 3.6 | 0.6
Before PR (fd451e63490d03b40eb74edc535f95457c0ad079)  | 179 | 13
After PR (0c608ec87358cf73f068d064f21ae09466b98ec1) | 28 | 5.8

\*\*Does not include download time

**Comment by tmfink** [comment]
~@m4b it looks like Travis-CI is not building pull requests automatically, any idea how to enable this?~

It looks like I just needed to push another commit to trigger the CI job.

**Comment by tmfink** [comment]
@m4b In reference to #2:

> 5. The feature flags aren't coherent - the lib.rs includes either the bundled or not-bundled depending on the feature flag, but use_system_capstone isn't reflected in this at all, nor is it depended on or dependent of the bundled flag

I purposely made these features independent:
* `use_bindgen` (instead of using the pre-generated bindings)
* `use_system_capstone` (instead of the bundled capstone library)

Why would we want to make the `use_system_capstone` dependent on `use_bindgen`?

**Comment by tmfink** [comment]
@m4b In reference to #2:

> 2. None of the bindings are documented anymore!

> I'm not even convinced this is a motivating usecase for the capstone bindings. As far as I know, the capstone ABI has been pretty rock-solid; I can't remember the last time it was changed, and I suspect it won't change anytime soon. 

I think that agree that losing the documentation for the types/functions, however:
1. Hopefully `bindgen` will eventually re-add support for adding documentation comments for types. It was disabled because some C++ comments were not valid markdown. See [bindgen issue #800].(https://github.com/rust-lang-nursery/rust-bindgen/issues/800)
2. Bindgen now generates Rust union types (instead of the confusing BindgenUnions)
3. The bindgen-generated bindings are generated exactly as expected from the capstone headers. The capstone headers are the documentation.
4. The HTML documentation generated by `cargo doc` is very useful. Example: https://docs.rs/capstone-sys/0.3.0/capstone_sys/

**Comment by m4b** [comment]
Personally, I don't want to find and open and peruse the capstone headers; sure they're documentation I suppose, but they don't show up when browsing docs.rs, which was a really nice feature.

Considering they were previously, its just seems like a feature regression.

Even if we just copy-paste the old doc headers from 0.2 for the pre-generated bindings, I think its better.

E.g., this just is nicer from a user standpoint:

screenshot from 2017-08-30 21-28-25

I don't really see the bindings being updated much since it now uses unions, which was probably the last stumbling block, yes? In that case it's probably safe to add the documentation to them, dunno.

On the other hand I can see how that's annoying and tediuous; but its sad to see them go, since they were there before, and it was easy to see what the functions and constants did, etc.

On other notes, since now emits unions, which I think was introduced in 1.19 (yes), and 1.18 won't work (which I just tried on)? We'll need to add that to the README, etc.

Otherwise, this looks 1000% better, great work!

I didn't understand why the compile time tripled, and then I realized the pre-generated bindings file was 8k :]

**Comment by m4b** [comment]
Should also add 1.19 is required for capstone-rs when this gets pushed

**Comment by m4b** [comment]
:( I just doc'd everything but i can't push to your branch

**Comment by tmfink** [comment]
> Haven't had a chance to glance at this but this has some good info: https://users.rust-lang.org/t/help-creating-a-sys-crate/12624/3?u=m4b
> I also didn't realize that pkgconfig doesn't work on windows :/
> I think in that case we should probably build the bundled bindings unconditionally?

That post has some good ideas.

We already:
* Follow the convention for
    a. statically linking the bundled `capstone`
    b. dynamically linking the system `capstone`
* Only write to `$OUT_DIR`
* Run a single command to compile the bundled `capstone`
* Keep a bundled copy of `bindgen`
* Keep a pre-generated copy of the `bindgen` output

Maybe we should also:
* Support Windows better. Luckily, `pkg-config` is only used when dynamically linking the system `capstone`, which is not the default. We can try to use the `vcpkg` crate (or some alternative). We could also state that we only support static linking for Windows. Luckily, the decision to use the bundled bindings is independent of the decision to use `bindgen`.

**Comment by tmfink** [comment]
@m4b we need to automate the documentation step. I suppose the good news is that we don't need to write code that works in general--our code only needs to understand capstone's doc comments. Since we only need to "autodoc" code to run ourselves, we could even write the code in Python or shell script.

I think that the "autodoc" feature should be a separate issue/PR.

I also agree that we should document Rust 1.19 or greater is required. I'll add it to the README.

**Comment by tmfink** [comment]
@m4b I cherry-picked your doc commit and added some clarification as to the provenance of the documentation. Merging per your comment.

**Comment by m4b** [comment]
@tmfink want me to publish 0.5? Also did you increment the version to 0.5?

**Comment by tmfink** [comment]
A release sounds good--I did not increment the version number.

**Comment by m4b** [comment]
Ok can you just set to 0.5 and push to master. I don't have master push rights afaics

**Comment by m4b** [comment]
nvm i'm stupid :D

**Comment by tmfink** [comment]
:D

**Comment by m4b** [comment]
ok published, really great work @tmfink, compile times are slim, great defaults, and now has complete capstone bindings with some hacked documentation, literally 1000% better :)

**Pull request merged**
